CREATE TABLE SHIPPING (
    SHIPPING_ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 101,  INCREMENT BY 1),
    STREET VARCHAR(50),
    SUBURB VARCHAR(30),
    STATE VARCHAR(3),
    POSTCODE VARCHAR(4),
    METHOD VARCHAR(50),
    DATE VARCHAR(20)
);