CREATE TABLE STAFF (
    ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 201,  INCREMENT BY 1),
    EMAIL VARCHAR(50) UNIQUE,
    PASSWORD VARCHAR(50),
    FULLNAME VARCHAR(50),
    POSITION VARCHAR(50),
    PHONENUM VARCHAR(10)
);